name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      # run tests
      - name: Run tests
        run: pytest -q

  docker:
    runs-on: ubuntu-latest
    needs: test  # only run if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # set up Docker
      - name: Build Docker image
        run: docker build -t ml-deploy-fastapi .
